nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    volumes_from:
        - app
        
app:
    image: alpine:3.6
    volumes:
        - ./project/app:/var/www/html/app
        - ./sites:/var/www/html/sites
    command: "true"