nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    volumes_from:
        - app
        
app:
    image: alpine:3.6
    volumes:
        - ./dist:/var/www/html/master
        - ./versions:/var/www/html/versions
    command: "true"