---
- hosts: all
  user: evermade
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    username: evermade
    dist_dir: /code/project/app
    remote_dir: /srv/www/deploy2.0/sites/versions
  roles:
   - { role: deploy, tags: [deploy] }