---
- name: Get Commit
  command: git rev-parse --short HEAD
  delegate_to: localhost
  args:
    chdir: "{{ dist_dir }}"
  register: gitcommit

- name: Creates directory
  file: 
    path: "{{ remote_dir }}/{{ gitcommit.stdout }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}" 
    mode: 0755 

- name: Copy files
  synchronize:
    src: "{{ dist_dir }}/" # my ansible container code location when mounted
    dest: "{{ remote_dir }}/{{ gitcommit.stdout }}/"
    recursive: true
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=node_modules"

- debug: msg="SHA-1 is {{ gitcommit.stdout }}"