---
- name: Get Commit
  command: git rev-parse --short HEAD
  args:
    chdir: "{{ dist_dir }}"
  register: gitcommit

- name: Creates directory
  file: 
    path: "{{ versions_dir }}/{{ gitcommit.stdout }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}" 
    mode: 0755 

- name: Copy files
  synchronize:
    src: /code/dist/ # my ansible container code location when mounted
    dest: "{{ versions_dir }}/{{ gitcommit.stdout }}/"

- debug: msg="SHA-1 is {{ gitcommit.stdout }}"